---
name: Data-Phrasebook-Loader-JSON-Syck
version: 0.01
author:
  - Stevan Little E<lt>stevan@iinteractive.comE<gt>
abstract: A Data::Phrasebook loader for JSON files
license: perl
requires:
  Carp: 0
  Data::Phrasebook: 0
  File::Slurp: 0
  JSON::Syck: 0
build_requires:
  File::Spec: 0
  FindBin: 0
  Test::Exception: 0.21
  Test::More: 0.47
provides:
  Data::Phrasebook::Loader::JSON::Syck:
    file: lib/Data/Phrasebook/Loader/JSON/Syck.pm
    version: 0.01
generated_by: Module::Build version 0.2611
